/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/buyer/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách đơn hàng đã mua của buyer */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buyer/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Xem chi tiết đơn hàng (buyer hoặc seller của đơn đó mới được xem) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID đơn hàng */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buyer/orders/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Huỷ đơn hàng (chỉ khi đơn đang ở trạng thái Created hoặc AwaitingSellerConfirmation) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID đơn hàng */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Lý do huỷ */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CancelOrderRequestDto"];
                    "text/json": components["schemas"]["CancelOrderRequestDto"];
                    "application/*+json": components["schemas"]["CancelOrderRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buyer/orders/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Gửi đánh giá cho đơn hàng đã hoàn thành (mỗi đơn chỉ đánh giá được 1 lần) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID đơn hàng */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Đánh giá sao (1-5) và nhận xét */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateReviewRequestDto"];
                    "text/json": components["schemas"]["CreateReviewRequestDto"];
                    "application/*+json": components["schemas"]["CreateReviewRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buyer/orders/{id}/tracking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy thông tin tracking vận chuyển thực tế từ Logistics Microservice */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID đơn hàng */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buyer/favorites/{postingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Thêm tin đăng vào danh sách yêu thích */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID tin đăng */
                    postingId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        /** Xoá tin đăng khỏi danh sách yêu thích */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID tin đăng */
                    postingId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buyer/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách tin đăng yêu thích của buyer */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tạo lệnh thanh toán mua xe — trả về QR VietQR để buyer quét
         * @description Purpose: `DEPOSIT` (10%) | `FULL_PAYMENT` (100%)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateOrderPaymentDto"];
                    "text/json": components["schemas"]["CreateOrderPaymentDto"];
                    "application/*+json": components["schemas"]["CreateOrderPaymentDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/status/{paymentCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kiểm tra trạng thái thanh toán (dùng cho FE polling sau khi hiện QR) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    paymentCode: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buyer/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy lịch sử đánh giá (bình luận) của buyer đang đăng nhập */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buyer/reviews/{postingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đăng đánh giá / bình luận trên một tin đăng */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID tin đăng cần đánh giá */
                    postingId: number;
                };
                cookie?: never;
            };
            /** @description Nội dung đánh giá */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PostCommentRequestDto"];
                    "text/json": components["schemas"]["PostCommentRequestDto"];
                    "application/*+json": components["schemas"]["PostCommentRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CancelOrderRequestDto: {
            reason?: string | null;
        };
        CreateOrderPaymentDto: {
            /** Format: int64 */
            postingId?: number;
            purpose?: string | null;
        };
        CreateReviewRequestDto: {
            /** Format: int32 */
            rating?: number;
            comment?: string | null;
        };
        PostCommentRequestDto: {
            content?: string | null;
        };
        ResponseModel: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            statusCode?: number;
            status?: string | null;
            message?: string | null;
            data?: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
