/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/payments/vip-package": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tạo lệnh thanh toán mua gói VIP để đẩy tin */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateVipPackagePaymentDto"];
                    "text/json": components["schemas"]["CreateVipPackagePaymentDto"];
                    "application/*+json": components["schemas"]["CreateVipPackagePaymentDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/postings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách tin đăng của seller đang đăng nhập */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        /** Tạo tin đăng mới */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Thông tin tin đăng, xe, và media */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreatePostingDto"];
                    "text/json": components["schemas"]["CreatePostingDto"];
                    "application/*+json": components["schemas"]["CreatePostingDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/postings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Xem chi tiết một tin đăng (kèm thông tin xe và ảnh) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID tin đăng */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        /** Cập nhật tin đăng (tin đã duyệt sẽ quay về trạng thái Waiting) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID tin đăng */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Thông tin cần cập nhật */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdatePostingDto"];
                    "text/json": components["schemas"]["UpdatePostingDto"];
                    "application/*+json": components["schemas"]["UpdatePostingDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        post?: never;
        /** Xóa tin đăng */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID tin đăng */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lấy danh sách đơn hàng bán của seller */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Xác nhận đơn hàng (seller sẵn sàng giao hàng) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID đơn hàng */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Từ chối đơn hàng (seller không muốn bán) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID đơn hàng */
                    id: number;
                };
                cookie?: never;
            };
            /** @description Lý do từ chối */
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RejectOrderRequestDto"];
                    "text/json": components["schemas"]["RejectOrderRequestDto"];
                    "application/*+json": components["schemas"]["RejectOrderRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/seller/orders/sales-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lịch sử bán hàng (buyer contact info chỉ hiện sau khi payment xác nhận) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResponseModel"];
                        "application/json": components["schemas"]["ResponseModel"];
                        "text/json": components["schemas"]["ResponseModel"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateBicycleDto: {
            /** Format: int64 */
            categoryId?: number | null;
            brand?: string | null;
            model?: string | null;
            frameSize?: string | null;
            /** Format: int32 */
            year?: number | null;
            condition?: string | null;
            color?: string | null;
            frameMaterial?: string | null;
            drivetrain?: string | null;
            wheelsAndTires?: string | null;
            brakeSystem?: string | null;
            description?: string | null;
        };
        CreatePostingDto: {
            title?: string | null;
            /** Format: double */
            price?: number;
            description?: string | null;
            isInspected?: boolean;
            bicycle?: components["schemas"]["CreateBicycleDto"];
            media?: components["schemas"]["MediaDto"][] | null;
        };
        CreateVipPackagePaymentDto: {
            /** Format: int64 */
            packageId?: number;
            /** Format: int64 */
            postingId?: number;
            includePostingFee?: boolean;
            includeInspectionFee?: boolean;
        };
        MediaDto: {
            url?: string | null;
            type?: string | null;
            /** Format: int32 */
            sortOrder?: number;
        };
        RejectOrderRequestDto: {
            reason?: string | null;
        };
        ResponseModel: {
            /** Format: int32 */
            id?: number;
            /** Format: int32 */
            statusCode?: number;
            status?: string | null;
            message?: string | null;
            data?: unknown;
        };
        UpdateBicycleDto: {
            /** Format: int64 */
            categoryId?: number | null;
            brand?: string | null;
            model?: string | null;
            frameSize?: string | null;
            /** Format: int32 */
            year?: number | null;
            condition?: string | null;
            color?: string | null;
            frameMaterial?: string | null;
            drivetrain?: string | null;
            wheelsAndTires?: string | null;
            brakeSystem?: string | null;
            description?: string | null;
        };
        UpdatePostingDto: {
            title?: string | null;
            /** Format: double */
            price?: number | null;
            description?: string | null;
            isInspected?: boolean | null;
            bicycle?: components["schemas"]["UpdateBicycleDto"];
            media?: components["schemas"]["MediaDto"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
